### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by awsms** [daot/bcdl#10]
```
⋊> ~/appz/bcdl on master ◦ go run bcdl.go https://cameleonrecords.bandcamp.com/music/                                                                                                                                                  01:58:03

     __                        __  __
    /  |                      /  |/  |
    ## |____    _______   ____## |## |
    ##      \  /       | /    ## |## |
    #######  |/#######/ /####### |## |
    ## |  ## |## |      ## |  ## |## |
    ## |__## |## \_____ ## \__## |## |
    ##    ##/ ##       |##    ## |## |
    #######/   #######/  #######/ ##/

==> https://cameleonrecords.bandcamp.com/music/
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x7ac712]

goroutine 1 [running]:
github.com/anaskhan96/soup.Root.Attrs(...)
	/home/me/go/pkg/mod/github.com/anaskhan96/soup@v1.2.4/soup.go:401
main.validateLink({0x7ffc52e235b3?, 0xc000014020?})
	/home/me/appz/bcdl/bcdl.go:646 +0x1d2
main.get({0x7ffc52e235b3, 0x2b})
	/home/me/appz/bcdl/bcdl.go:658 +0xcb
main.main()
	/home/me/appz/bcdl/bcdl.go:795 +0x142c
exit status 2
```

Got this error while trying to dl https://cameleonrecords.bandcamp.com/

**Comment by daot** [comment]
Fixed in latest release!
